---
name: "AnimeThemesSync"
guid: "66d528df-4632-4d43-9828-56957262572b"
imageUrl: https://raw.githubusercontent.com/CassisCloud/jellyfin-plugin-animethemes-sync/refs/heads/main/resource/images/jellyfin-plugin-animethemes-sync.jpeg
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Automatically downloads anime OP/ED themes from AnimeThemes.moe for your Jellyfin library."
description: >
  Automatically download OP/ED videos from AnimeThemes.moe to upgrade your collection!

  Key Features:
  - Precise Matching: Uses AniList/MyAnimeList IDs to ensure the correct anime.
  - Smart Tagging: Automatically adds season tags like 'Winter 2024'.
  - Direct Links: Quick access to the source pages on AnimeThemes.moe.
category: "Anime"
owner: "CassisCloud"
artifacts:
- "Jellyfin.Plugin.AnimeThemesSync.dll"
changelog: >
  Initial release.
