---
name: "AnimeThemesSync"
guid: "66d528df-4632-4d43-9828-56957262572b"
imageUrl: https://github.com/CassisCloud/jellyfin-plugin-animethemes-sync/raw/refs/heads/main/resource/images/jellyfin-plugin-animethemes-sync.jpeg
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Syncs anime themes (OPs and EDs) from animethemes.moe to Jellyfin"
description: >
  Plugin for Jellyfin that syncs anime theme songs (OPs and EDs) from animethemes.moe.
  Requires the AniDB plugin to be installed for AniDB ID matching.
category: "Metadata"
owner: "CassisCloud"
artifacts:
- "Jellyfin.Plugin.AnimeThemesSync.dll"
changelog: >
  Initial release.
